In [35]:
features_churn = df.groupby("features_used").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

features_churn["churn_rate"] = (
    features_churn["churn_rate"] * 100
)

features_churn.sort_values("features_used")

               customers  churned_customers  churn_rate
features_used
1                    424                 39    9.198113
2                    834                 82    9.832134
3                   1394                143   10.258250
4                   1767                183   10.356537
5                   1746                187   10.710195
6                   1501                154   10.259827
7                   1013                 93    9.180652
8                    656                 64    9.756098
9                    359                 44   12.256267
10                   185                 15    8.108108
11                    69                  9   13.043478
12                    30                  5   16.666667
13                    18                  2   11.111111
14                     3                  0    0.000000
15                     1                  1  100.000000

In [36]:
features_churn

               customers  churned_customers  churn_rate
features_used
1                    424                 39    9.198113
2                    834                 82    9.832134
3                   1394                143   10.258250
4                   1767                183   10.356537
5                   1746                187   10.710195
6                   1501                154   10.259827
7                   1013                 93    9.180652
8                    656                 64    9.756098
9                    359                 44   12.256267
10                   185                 15    8.108108
11                    69                  9   13.043478
12                    30                  5   16.666667
13                    18                  2   11.111111
14                     3                  0    0.000000
15                     1                  1  100.000000

In [37]:
usage_growth_churn = df.groupby("usage_growth_rate").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

usage_growth_churn["churn_rate"] = (
    usage_growth_churn["churn_rate"] * 100
)

usage_growth_churn.sort_values("usage_growth_rate")

                   customers  churned_customers  churn_rate
usage_growth_rate
-0.58                      1                  0    0.000000
-0.54                      1                  0    0.000000
-0.51                      1                  0    0.000000
-0.46                      1                  1  100.000000
-0.45                      9                  1   11.111111
...                      ...                ...         ...
 0.50                      1                  0    0.000000
 0.51                      2                  0    0.000000
 0.52                      1                  0    0.000000
 0.53                      2                  0    0.000000
 0.54                      1                  1  100.000000

[104 rows x 3 columns]

In [39]:
df["usage_growth_band"] = pd.cut(
    df["usage_growth_rate"],
    bins=[-float("inf"), -0.10, 0, 0.10, float("inf")],
    labels=[
        "Declining (< -10%)",
        "Slightly Declining (-10% to 0%)",
        "Slightly Growing (0% to 10%)",
        "Growing (> 10%)"
    ]
)

In [40]:
usage_growth_churn = df.groupby(
    "usage_growth_band",
    observed=True
).agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

usage_growth_churn["churn_rate"] = (
    usage_growth_churn["churn_rate"] * 100
)

usage_growth_churn

                                 customers  churned_customers  churn_rate
usage_growth_band
Declining (< -10%)                    2205                221   10.022676
Slightly Declining (-10% to 0%)       2431                236    9.707939
Slightly Growing (0% to 10%)          2546                262   10.290652
Growing (> 10%)                       2818                302   10.716820

So far, our strongest signals are:

🔥 1. Monthly engagement

Customers with 0–4 monthly logins → 28.59% churn

Compared with overall churn of 10.21%.

🔥 2. Payment failures

Customers with 2 payment failures → 25.26% churn

Compared with about 8.7% for 0–1 failures.

These are much more interesting than features_used or usage_growth_rate.

In [41]:
support_churn = df.groupby("support_tickets").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

support_churn["churn_rate"] = (
    support_churn["churn_rate"] * 100
)

support_churn.sort_values("support_tickets")

                 customers  churned_customers  churn_rate
support_tickets
0                     3012                315   10.458167
1                     3609                353    9.781103
2                     2124                215   10.122411
3                      908                108   11.894273
4                      273                 26    9.523810
5                       56                  3    5.357143
6                       13                  0    0.000000
7                        5                  1   20.000000

In [42]:
support_churn

                 customers  churned_customers  churn_rate
support_tickets
0                     3012                315   10.458167
1                     3609                353    9.781103
2                     2124                215   10.122411
3                      908                108   11.894273
4                      273                 26    9.523810
5                       56                  3    5.357143
6                       13                  0    0.000000
7                        5                  1   20.000000

In [43]:
csat_churn = df.groupby("csat_score").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

csat_churn["churn_rate"] = (
    csat_churn["churn_rate"] * 100
)

csat_churn.sort_values("csat_score")

            customers  churned_customers  churn_rate
csat_score
1                 221                 52   23.529412
2                1322                344   26.021180
3                3380                268    7.928994
4                3523                237    6.727221
5                1554                120    7.722008

In [44]:
csat_churn

            customers  churned_customers  churn_rate
csat_score
1                 221                 52   23.529412
2                1322                344   26.021180
3                3380                268    7.928994
4                3523                237    6.727221
5                1554                120    7.722008

In [45]:
complaint_churn = df.groupby("complaint_type").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

complaint_churn["churn_rate"] = (
    complaint_churn["churn_rate"] * 100
)

complaint_churn.sort_values(
    "churn_rate",
    ascending=False
)

                customers  churned_customers  churn_rate
complaint_type
Technical            3498                361   10.320183
None                 2045                211   10.317848
Billing              2427                247   10.177173
Service              2030                202    9.950739

In [46]:
nps_churn = df.groupby("nps_score").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

nps_churn["churn_rate"] = (
    nps_churn["churn_rate"] * 100
)

nps_churn.sort_values("nps_score")

           customers  churned_customers  churn_rate
nps_score
-100              14                  0    0.000000
-98                2                  0    0.000000
-95                4                  1   25.000000
-94                1                  0    0.000000
-93                4                  1   25.000000
...              ...                ...         ...
 96               11                  1    9.090909
 97               16                  0    0.000000
 98               14                  2   14.285714
 99               17                  1    5.882353
 100             244                 26   10.655738

[197 rows x 3 columns]

In [47]:
nps_churn

           customers  churned_customers  churn_rate
nps_score
-100              14                  0    0.000000
-98                2                  0    0.000000
-95                4                  1   25.000000
-94                1                  0    0.000000
-93                4                  1   25.000000
...              ...                ...         ...
 96               11                  1    9.090909
 97               16                  0    0.000000
 98               14                  2   14.285714
 99               17                  1    5.882353
 100             244                 26   10.655738

[197 rows x 3 columns]

In [48]:
df["nps_band"] = pd.cut(
    df["nps_score"],
    bins=[-101, -1, 49, 100],
    labels=[
        "Detractors",
        "Passives",
        "Promoters"
    ]
)

In [49]:
nps_band_churn = df.groupby(
    "nps_band",
    observed=True
).agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

nps_band_churn["churn_rate"] = (
    nps_band_churn["churn_rate"] * 100
)

nps_band_churn

            customers  churned_customers  churn_rate
nps_band
Detractors       3009                292    9.704221
Passives         4742                507   10.691691
Promoters        2249                222    9.871054

In [50]:
escalation_churn = df.groupby("escalations").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

escalation_churn["churn_rate"] = (
    escalation_churn["churn_rate"] * 100
)

escalation_churn

             customers  churned_customers  churn_rate
escalations
0                 7445                748   10.047011
1                 2216                236   10.649819
2                  296                 31   10.472973
3                   39                  6   15.384615
4                    4                  0    0.000000

In [51]:
df["resolution_time_band"] = pd.cut(
    df["avg_resolution_time"],
    bins=[-float("inf"), 10, 20, 30, 40, float("inf")],
    labels=[
        "<10",
        "10-20",
        "20-30",
        "30-40",
        "40+"
    ]
)

In [52]:
resolution_churn = df.groupby(
    "resolution_time_band",
    observed=True
).agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

resolution_churn["churn_rate"] = (
    resolution_churn["churn_rate"] * 100
)

resolution_churn

                      customers  churned_customers  churn_rate
resolution_time_band
<10                         834                 76    9.112710
10-20                      2630                296   11.254753
20-30                      3794                383   10.094887
30-40                      2185                212    9.702517
40+                         557                 54    9.694794

In [53]:
price_churn = df.groupby("price_increase_last_3m").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

price_churn["churn_rate"] = (
    price_churn["churn_rate"] * 100
)

price_churn

                        customers  churned_customers  churn_rate
price_increase_last_3m
No                           8055                819   10.167598
Yes                          1945                202   10.385604

In [54]:
discount_churn = df.groupby("discount_applied").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

discount_churn["churn_rate"] = (
    discount_churn["churn_rate"] * 100
)

discount_churn

                  customers  churned_customers  churn_rate
discount_applied
No                     6950                728   10.474820
Yes                    3050                293    9.606557

✅ "Customers receiving discounts had slightly lower observed churn, but the difference was modest."

In [55]:
segment_revenue_loss = df.groupby("customer_segment").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    total_revenue=("total_revenue", "sum"),
    churned_revenue=("total_revenue", lambda x: x[df.loc[x.index, "churn"] == 1].sum())
)

segment_revenue_loss["churn_rate"] = (
    segment_revenue_loss["churned_customers"]
    / segment_revenue_loss["customers"]
    * 100
)

segment_revenue_loss.sort_values(
    "churned_revenue",
    ascending=False
)

,customers,churned_customers,total_revenue,churned_revenue,churn_rate
customer_segment,,,,,
Individual,5984,597,6316310.0,495820.0,9.976604
SME,3029,331,3248910.0,290650.0,10.927699
Enterprise,987,93,1004960.0,76170.0,9.422492

In [56]:
contract_revenue_loss = df.groupby("contract_type").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    total_revenue=("total_revenue", "sum"),
    churned_revenue=(
        "total_revenue",
        lambda x: x[df.loc[x.index, "churn"] == 1].sum()
    )
)

contract_revenue_loss["churn_rate"] = (
    contract_revenue_loss["churned_customers"]
    / contract_revenue_loss["customers"]
    * 100
)

contract_revenue_loss.sort_values(
    "churned_revenue",
    ascending=False
)

,customers,churned_customers,total_revenue,churned_revenue,churn_rate
contract_type,,,,,
Monthly,4967,513,5239430.0,449970.0,10.328166
Quarterly,3050,303,3230690.0,239380.0,9.934426
Yearly,1983,205,2100060.0,173290.0,10.337872

Monthly contracts represent the largest revenue exposure from customer churn and should be a major retention priority.

In [57]:
payment_revenue_loss = df.groupby("payment_method").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    total_revenue=("total_revenue", "sum"),
    churned_revenue=(
        "total_revenue",
        lambda x: x[df.loc[x.index, "churn"] == 1].sum()
    )
)

payment_revenue_loss["churn_rate"] = (
    payment_revenue_loss["churned_customers"]
    / payment_revenue_loss["customers"]
    * 100
)

payment_revenue_loss.sort_values(
    "churned_revenue",
    ascending=False
)

,customers,churned_customers,total_revenue,churned_revenue,churn_rate
payment_method,,,,,
Card,5955,619,6295140.0,525080.0,10.394626
PayPal,2557,255,2688890.0,221710.0,9.972624
Bank Transfer,1488,147,1586150.0,115850.0,9.879032

In [58]:
payment_failure_revenue = df.groupby("payment_failures").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    total_revenue=("total_revenue", "sum"),
    churned_revenue=(
        "total_revenue",
        lambda x: x[df.loc[x.index, "churn"] == 1].sum()
    )
)

payment_failure_revenue["churn_rate"] = (
    payment_failure_revenue["churned_customers"]
    / payment_failure_revenue["customers"]
    * 100
)

payment_failure_revenue.sort_values("payment_failures")

,customers,churned_customers,total_revenue,churned_revenue,churn_rate
payment_failures,,,,,
0,6084,533,6405540.0,456730.0,8.760684
1,2989,259,3144960.0,198160.0,8.665105
2,780,197,825360.0,172880.0,25.256410
3,130,28,179080.0,32300.0,21.538462
4,14,3,12740.0,2410.0,21.428571
5,3,1,2500.0,160.0,33.333333

In [59]:
df["inactivity_band"] = pd.cut(
    df["last_login_days_ago"],
    bins=[-1, 7, 14, 30, 60, float("inf")],
    labels=[
        "0-7 days",
        "8-14 days",
        "15-30 days",
        "31-60 days",
        "60+ days"
    ]
)

In [60]:
inactivity_churn = df.groupby(
    "inactivity_band",
    observed=True
).agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

inactivity_churn["churn_rate"] = (
    inactivity_churn["churn_rate"] * 100
)

inactivity_churn

                 customers  churned_customers  churn_rate
inactivity_band
0-7 days              5480                545    9.945255
8-14 days             2328                229    9.836770
15-30 days            1766                164    9.286523
31-60 days             410                 80   19.512195
60+ days                16                  3   18.750000

Customer inactivity becomes a significant churn signal after approximately 30 days, with the 31–60 day segment showing nearly double the churn rate of customers inactive for 30 days or less.

In [61]:
df["usage_growth_band"] = pd.cut(
    df["usage_growth_rate"],
    bins=[-float("inf"), -20, -10, 0, 10, 20, float("inf")],
    labels=[
        "< -20%",
        "-20% to -10%",
        "-10% to 0%",
        "0% to 10%",
        "10% to 20%",
        "20%+"
    ]
)

In [62]:
usage_growth_churn = df.groupby(
    "usage_growth_band",
    observed=True
).agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

usage_growth_churn["churn_rate"] = (
    usage_growth_churn["churn_rate"] * 100
)

usage_growth_churn

                   customers  churned_customers  churn_rate
usage_growth_band
-10% to 0%              4636                457    9.857636
0% to 10%               5364                564   10.514541

Usage growth rate does not show a meaningful difference in churn between the observed bands, suggesting that usage growth alone is not a strong churn predictor in this dataset.

In [64]:
df["tenure_band"] = pd.cut(
    df["tenure_months"],
    bins=[-1, 3, 6, 12, 24, float("inf")],
    labels=[
        "0-3 months",
        "4-6 months",
        "7-12 months",
        "13-24 months",
        "24+ months"
    ]
)

In [65]:
tenure_churn = df.groupby(
    "tenure_band",
    observed=True
).agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

tenure_churn["churn_rate"] = (
    tenure_churn["churn_rate"] * 100
)

tenure_churn

              customers  churned_customers  churn_rate
tenure_band
0-3 months          520                167   32.115385
4-6 months          512                123   24.023438
7-12 months        1018                 90    8.840864
13-24 months       1987                174    8.756920
24+ months         5963                467    7.831628

In [66]:
signup_churn = df.groupby("signup_channel").agg(
    customers=("customer_id", "count"),
    churned_customers=("churn", "sum"),
    churn_rate=("churn", "mean")
)

signup_churn["churn_rate"] = (
    signup_churn["churn_rate"] * 100
)

signup_churn.sort_values(
    "churn_rate",
    ascending=False
)

                customers  churned_customers  churn_rate
signup_channel
Referral             2004                224   11.177645
Mobile               2960                296   10.000000
Web                  5036                501    9.948372